// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using muchik.market.pay.infrastructure.context;

#nullable disable

namespace muchik.market.pay.infrastructure.Migrations
{
    [DbContext(typeof(PayContext))]
    [Migration("20231022215515_Migracion1-Api")]
    partial class Migracion1Api
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("muchik.market.pay.domain.entities.Pay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("pay", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
